context:
  name: essreflectometry
  version: "26.9.1"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essreflectometry-${{ version }}.tar.gz
  sha256: bff1a69d85f7a485d4d9f07cd42061efa3a1bff75c8fc87eefdd0641f2b89dab

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core >=2022.1.0
    - python-graphviz >=0.20
    - mcstastox >=0.0.11
    - python-dateutil >=2.9.0
    - plopp >=26.5.0
    - orsopy >=1.2
    - essreduce >=26.6.0
    - esspolarization >=25.7.0
    - pandas >=2.1.2
    - scippneutron >=26.9.0

tests:
  - python:
      imports:
        - ess.reflectometry
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Reflectometry data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/ess/tree/main/packages/essreflectometry
  homepage: https://scipp.github.io/ess/reflectometry/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
