context:
  name: essreflectometry
  version: "26.2.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essreflectometry-${{ version }}.tar.gz
  sha256: 6bd13d1e592af9fb8aabc4505fbe5e3993b5e64e6886a5dd11d304794a576809

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core >=2022.1.0
    - python-dateutil
    - python-graphviz
    - plopp >=24.7.0
    - orsopy >=1.2
    - sciline >=24.6.0
    - scipp >=24.09.1
    - scippneutron >=24.10.0
    - scippnexus >=24.9.1
    - esspolarization >=25.7.0
    - essreduce >=25.11.0
    - pandas >=2.1.2

tests:
  - python:
      imports:
        - ess.reflectometry
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Reflectometry data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/essreflectometry
  homepage: https://scipp.github.io/essreflectometry/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
